'use strict'

exports.__esModule = true
exports.INCREMENT = 'INCREMENT'
exports.DELETE_TODO = 'DELETE_TODO'
exports.EDIT_TODO = 'EDIT_TODO'
exports.COMPLETE_TODO = 'COMPLETE_TODO'
exports.COMPLETE_ALL_TODOS = 'COMPLETE_ALL_TODOS'
exports.CLEAR_COMPLETED = 'CLEAR_COMPLETED'
exports.SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
